// Code generated by entc, DO NOT EDIT.

package installation

import (
	"time"
)

const (
	// Label holds the string label denoting the installation type in the database.
	Label = "installation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeModuleVersion holds the string denoting the moduleversion edge name in mutations.
	EdgeModuleVersion = "moduleVersion"
	// Table holds the table name of the installation in the database.
	Table = "installations"
	// ModuleVersionTable is the table that holds the moduleVersion relation/edge.
	ModuleVersionTable = "installations"
	// ModuleVersionInverseTable is the table name for the ModuleVersion entity.
	// It exists in this package in order to avoid circular dependency with the "moduleversion" package.
	ModuleVersionInverseTable = "module_versions"
	// ModuleVersionColumn is the table column denoting the moduleVersion relation/edge.
	ModuleVersionColumn = "module_version_installations"
)

// Columns holds all SQL columns for installation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "installations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"module_version_installations",
	"namespace_installations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
