root = "." 
tmp_dir = ".air"

[build]
cmd = "go build -o ./.air/selfservice main.go"
bin = ".air/selfservice server"
include_ext = ["go"]
exclude_dir = ["public", "src", "dist", "data", "node_modules"]

[misc]
clean_on_exit = true
