---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
spec:
  template:
    metadata:
      name: api
    spec:
      containers:
        - image: ${IMAGE}
          ports:
            - containerPort: 80
          env:
            - name: TARGET
              value: "World"
