// Code generated by entc, DO NOT EDIT.

package moduleversion

import (
	"time"
)

const (
	// Label holds the string label denoting the moduleversion type in the database.
	Label = "module_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeModule holds the string denoting the module edge name in mutations.
	EdgeModule = "module"
	// Table holds the table name of the moduleversion in the database.
	Table = "module_versions"
	// ModuleTable is the table that holds the module relation/edge.
	ModuleTable = "module_versions"
	// ModuleInverseTable is the table name for the Module entity.
	// It exists in this package in order to avoid circular dependency with the "module" package.
	ModuleInverseTable = "modules"
	// ModuleColumn is the table column denoting the module relation/edge.
	ModuleColumn = "module_versions"
)

// Columns holds all SQL columns for moduleversion fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldSource,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "module_versions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"module_versions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
