// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (m *ModuleQuery) CollectFields(ctx context.Context, satisfies ...string) *ModuleQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		m = m.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return m
}

func (m *ModuleQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *ModuleQuery {
	return m
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (mv *ModuleVersionQuery) CollectFields(ctx context.Context, satisfies ...string) *ModuleVersionQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		mv = mv.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return mv
}

func (mv *ModuleVersionQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *ModuleVersionQuery {
	return mv
}
