// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meringu/selfserve/pkg/api/ent/installation"
	"github.com/meringu/selfserve/pkg/api/ent/moduleversion"
)

// InstallationCreate is the builder for creating a Installation entity.
type InstallationCreate struct {
	config
	mutation *InstallationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ic *InstallationCreate) SetCreatedAt(t time.Time) *InstallationCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InstallationCreate) SetNillableCreatedAt(t *time.Time) *InstallationCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetModuleVersionID sets the "moduleVersion" edge to the ModuleVersion entity by ID.
func (ic *InstallationCreate) SetModuleVersionID(id int) *InstallationCreate {
	ic.mutation.SetModuleVersionID(id)
	return ic
}

// SetNillableModuleVersionID sets the "moduleVersion" edge to the ModuleVersion entity by ID if the given value is not nil.
func (ic *InstallationCreate) SetNillableModuleVersionID(id *int) *InstallationCreate {
	if id != nil {
		ic = ic.SetModuleVersionID(*id)
	}
	return ic
}

// SetModuleVersion sets the "moduleVersion" edge to the ModuleVersion entity.
func (ic *InstallationCreate) SetModuleVersion(m *ModuleVersion) *InstallationCreate {
	return ic.SetModuleVersionID(m.ID)
}

// Mutation returns the InstallationMutation object of the builder.
func (ic *InstallationCreate) Mutation() *InstallationMutation {
	return ic.mutation
}

// Save creates the Installation in the database.
func (ic *InstallationCreate) Save(ctx context.Context) (*Installation, error) {
	var (
		err  error
		node *Installation
	)
	ic.defaults()
	if len(ic.hooks) == 0 {
		if err = ic.check(); err != nil {
			return nil, err
		}
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InstallationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ic.check(); err != nil {
				return nil, err
			}
			ic.mutation = mutation
			if node, err = ic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			if ic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InstallationCreate) SaveX(ctx context.Context) *Installation {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InstallationCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InstallationCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InstallationCreate) defaults() {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := installation.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InstallationCreate) check() error {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	return nil
}

func (ic *InstallationCreate) sqlSave(ctx context.Context) (*Installation, error) {
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ic *InstallationCreate) createSpec() (*Installation, *sqlgraph.CreateSpec) {
	var (
		_node = &Installation{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: installation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: installation.FieldID,
			},
		}
	)
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: installation.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := ic.mutation.ModuleVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   installation.ModuleVersionTable,
			Columns: []string{installation.ModuleVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: moduleversion.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.module_version_installations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InstallationCreateBulk is the builder for creating many Installation entities in bulk.
type InstallationCreateBulk struct {
	config
	builders []*InstallationCreate
}

// Save creates the Installation entities in the database.
func (icb *InstallationCreateBulk) Save(ctx context.Context) ([]*Installation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Installation, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstallationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InstallationCreateBulk) SaveX(ctx context.Context) []*Installation {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InstallationCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InstallationCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
