// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/meringu/selfserve/pkg/api/ent/installation"
	"github.com/meringu/selfserve/pkg/api/ent/module"
	"github.com/meringu/selfserve/pkg/api/ent/moduleversion"
	"github.com/meringu/selfserve/pkg/api/ent/predicate"
)

// ModuleVersionQuery is the builder for querying ModuleVersion entities.
type ModuleVersionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ModuleVersion
	// eager-loading edges.
	withModule        *ModuleQuery
	withInstallations *InstallationQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModuleVersionQuery builder.
func (mvq *ModuleVersionQuery) Where(ps ...predicate.ModuleVersion) *ModuleVersionQuery {
	mvq.predicates = append(mvq.predicates, ps...)
	return mvq
}

// Limit adds a limit step to the query.
func (mvq *ModuleVersionQuery) Limit(limit int) *ModuleVersionQuery {
	mvq.limit = &limit
	return mvq
}

// Offset adds an offset step to the query.
func (mvq *ModuleVersionQuery) Offset(offset int) *ModuleVersionQuery {
	mvq.offset = &offset
	return mvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mvq *ModuleVersionQuery) Unique(unique bool) *ModuleVersionQuery {
	mvq.unique = &unique
	return mvq
}

// Order adds an order step to the query.
func (mvq *ModuleVersionQuery) Order(o ...OrderFunc) *ModuleVersionQuery {
	mvq.order = append(mvq.order, o...)
	return mvq
}

// QueryModule chains the current query on the "module" edge.
func (mvq *ModuleVersionQuery) QueryModule() *ModuleQuery {
	query := &ModuleQuery{config: mvq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moduleversion.Table, moduleversion.FieldID, selector),
			sqlgraph.To(module.Table, module.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, moduleversion.ModuleTable, moduleversion.ModuleColumn),
		)
		fromU = sqlgraph.SetNeighbors(mvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInstallations chains the current query on the "installations" edge.
func (mvq *ModuleVersionQuery) QueryInstallations() *InstallationQuery {
	query := &InstallationQuery{config: mvq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moduleversion.Table, moduleversion.FieldID, selector),
			sqlgraph.To(installation.Table, installation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, moduleversion.InstallationsTable, moduleversion.InstallationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModuleVersion entity from the query.
// Returns a *NotFoundError when no ModuleVersion was found.
func (mvq *ModuleVersionQuery) First(ctx context.Context) (*ModuleVersion, error) {
	nodes, err := mvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moduleversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mvq *ModuleVersionQuery) FirstX(ctx context.Context) *ModuleVersion {
	node, err := mvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModuleVersion ID from the query.
// Returns a *NotFoundError when no ModuleVersion ID was found.
func (mvq *ModuleVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moduleversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mvq *ModuleVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := mvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModuleVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ModuleVersion entity is not found.
// Returns a *NotFoundError when no ModuleVersion entities are found.
func (mvq *ModuleVersionQuery) Only(ctx context.Context) (*ModuleVersion, error) {
	nodes, err := mvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moduleversion.Label}
	default:
		return nil, &NotSingularError{moduleversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mvq *ModuleVersionQuery) OnlyX(ctx context.Context) *ModuleVersion {
	node, err := mvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModuleVersion ID in the query.
// Returns a *NotSingularError when exactly one ModuleVersion ID is not found.
// Returns a *NotFoundError when no entities are found.
func (mvq *ModuleVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = &NotSingularError{moduleversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mvq *ModuleVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := mvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModuleVersions.
func (mvq *ModuleVersionQuery) All(ctx context.Context) ([]*ModuleVersion, error) {
	if err := mvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mvq *ModuleVersionQuery) AllX(ctx context.Context) []*ModuleVersion {
	nodes, err := mvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModuleVersion IDs.
func (mvq *ModuleVersionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mvq.Select(moduleversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mvq *ModuleVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := mvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mvq *ModuleVersionQuery) Count(ctx context.Context) (int, error) {
	if err := mvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mvq *ModuleVersionQuery) CountX(ctx context.Context) int {
	count, err := mvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mvq *ModuleVersionQuery) Exist(ctx context.Context) (bool, error) {
	if err := mvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mvq *ModuleVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := mvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModuleVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mvq *ModuleVersionQuery) Clone() *ModuleVersionQuery {
	if mvq == nil {
		return nil
	}
	return &ModuleVersionQuery{
		config:            mvq.config,
		limit:             mvq.limit,
		offset:            mvq.offset,
		order:             append([]OrderFunc{}, mvq.order...),
		predicates:        append([]predicate.ModuleVersion{}, mvq.predicates...),
		withModule:        mvq.withModule.Clone(),
		withInstallations: mvq.withInstallations.Clone(),
		// clone intermediate query.
		sql:  mvq.sql.Clone(),
		path: mvq.path,
	}
}

// WithModule tells the query-builder to eager-load the nodes that are connected to
// the "module" edge. The optional arguments are used to configure the query builder of the edge.
func (mvq *ModuleVersionQuery) WithModule(opts ...func(*ModuleQuery)) *ModuleVersionQuery {
	query := &ModuleQuery{config: mvq.config}
	for _, opt := range opts {
		opt(query)
	}
	mvq.withModule = query
	return mvq
}

// WithInstallations tells the query-builder to eager-load the nodes that are connected to
// the "installations" edge. The optional arguments are used to configure the query builder of the edge.
func (mvq *ModuleVersionQuery) WithInstallations(opts ...func(*InstallationQuery)) *ModuleVersionQuery {
	query := &InstallationQuery{config: mvq.config}
	for _, opt := range opts {
		opt(query)
	}
	mvq.withInstallations = query
	return mvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModuleVersion.Query().
//		GroupBy(moduleversion.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mvq *ModuleVersionQuery) GroupBy(field string, fields ...string) *ModuleVersionGroupBy {
	group := &ModuleVersionGroupBy{config: mvq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mvq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ModuleVersion.Query().
//		Select(moduleversion.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (mvq *ModuleVersionQuery) Select(fields ...string) *ModuleVersionSelect {
	mvq.fields = append(mvq.fields, fields...)
	return &ModuleVersionSelect{ModuleVersionQuery: mvq}
}

func (mvq *ModuleVersionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mvq.fields {
		if !moduleversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mvq.path != nil {
		prev, err := mvq.path(ctx)
		if err != nil {
			return err
		}
		mvq.sql = prev
	}
	return nil
}

func (mvq *ModuleVersionQuery) sqlAll(ctx context.Context) ([]*ModuleVersion, error) {
	var (
		nodes       = []*ModuleVersion{}
		withFKs     = mvq.withFKs
		_spec       = mvq.querySpec()
		loadedTypes = [2]bool{
			mvq.withModule != nil,
			mvq.withInstallations != nil,
		}
	)
	if mvq.withModule != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, moduleversion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ModuleVersion{config: mvq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := mvq.withModule; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ModuleVersion)
		for i := range nodes {
			if nodes[i].module_versions == nil {
				continue
			}
			fk := *nodes[i].module_versions
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(module.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "module_versions" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Module = n
			}
		}
	}

	if query := mvq.withInstallations; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ModuleVersion)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Installations = []*Installation{}
		}
		query.withFKs = true
		query.Where(predicate.Installation(func(s *sql.Selector) {
			s.Where(sql.InValues(moduleversion.InstallationsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.module_version_installations
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "module_version_installations" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "module_version_installations" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Installations = append(node.Edges.Installations, n)
		}
	}

	return nodes, nil
}

func (mvq *ModuleVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mvq.querySpec()
	return sqlgraph.CountNodes(ctx, mvq.driver, _spec)
}

func (mvq *ModuleVersionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mvq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mvq *ModuleVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   moduleversion.Table,
			Columns: moduleversion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: moduleversion.FieldID,
			},
		},
		From:   mvq.sql,
		Unique: true,
	}
	if unique := mvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moduleversion.FieldID)
		for i := range fields {
			if fields[i] != moduleversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mvq *ModuleVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mvq.driver.Dialect())
	t1 := builder.Table(moduleversion.Table)
	columns := mvq.fields
	if len(columns) == 0 {
		columns = moduleversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mvq.sql != nil {
		selector = mvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range mvq.predicates {
		p(selector)
	}
	for _, p := range mvq.order {
		p(selector)
	}
	if offset := mvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModuleVersionGroupBy is the group-by builder for ModuleVersion entities.
type ModuleVersionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mvgb *ModuleVersionGroupBy) Aggregate(fns ...AggregateFunc) *ModuleVersionGroupBy {
	mvgb.fns = append(mvgb.fns, fns...)
	return mvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mvgb *ModuleVersionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mvgb.path(ctx)
	if err != nil {
		return err
	}
	mvgb.sql = query
	return mvgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mvgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mvgb.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) StringsX(ctx context.Context) []string {
	v, err := mvgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mvgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) StringX(ctx context.Context) string {
	v, err := mvgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mvgb.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) IntsX(ctx context.Context) []int {
	v, err := mvgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mvgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) IntX(ctx context.Context) int {
	v, err := mvgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mvgb.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mvgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mvgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mvgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mvgb.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mvgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mvgb *ModuleVersionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mvgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mvgb *ModuleVersionGroupBy) BoolX(ctx context.Context) bool {
	v, err := mvgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mvgb *ModuleVersionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mvgb.fields {
		if !moduleversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mvgb *ModuleVersionGroupBy) sqlQuery() *sql.Selector {
	selector := mvgb.sql.Select()
	aggregation := make([]string, 0, len(mvgb.fns))
	for _, fn := range mvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mvgb.fields)+len(mvgb.fns))
		for _, f := range mvgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mvgb.fields...)...)
}

// ModuleVersionSelect is the builder for selecting fields of ModuleVersion entities.
type ModuleVersionSelect struct {
	*ModuleVersionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mvs *ModuleVersionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mvs.prepareQuery(ctx); err != nil {
		return err
	}
	mvs.sql = mvs.ModuleVersionQuery.sqlQuery(ctx)
	return mvs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mvs *ModuleVersionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mvs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mvs.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mvs *ModuleVersionSelect) StringsX(ctx context.Context) []string {
	v, err := mvs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mvs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mvs *ModuleVersionSelect) StringX(ctx context.Context) string {
	v, err := mvs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mvs.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mvs *ModuleVersionSelect) IntsX(ctx context.Context) []int {
	v, err := mvs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mvs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mvs *ModuleVersionSelect) IntX(ctx context.Context) int {
	v, err := mvs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mvs.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mvs *ModuleVersionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mvs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mvs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mvs *ModuleVersionSelect) Float64X(ctx context.Context) float64 {
	v, err := mvs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mvs.fields) > 1 {
		return nil, errors.New("ent: ModuleVersionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mvs *ModuleVersionSelect) BoolsX(ctx context.Context) []bool {
	v, err := mvs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mvs *ModuleVersionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mvs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduleversion.Label}
	default:
		err = fmt.Errorf("ent: ModuleVersionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mvs *ModuleVersionSelect) BoolX(ctx context.Context) bool {
	v, err := mvs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mvs *ModuleVersionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mvs.sql.Query()
	if err := mvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
